export const EventTypes: {
  readonly USER_LOGGED_IN: 'USER_LOGGED_IN';
  readonly USER_LOGGED_OUT: 'USER_LOGGED_OUT';
  readonly NOTIFICATION_SHOW: 'NOTIFICATION_SHOW';
  readonly THEME_CHANGED: 'THEME_CHANGED';
} = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',
  THEME_CHANGED: 'THEME_CHANGED',
} as const;
